---
title: "Individual analysis amateur players Surrogate HRV"
output: html_notebook
---

```{r}
## load data and packages
rm(list=ls())
require(nonlinearTseries)
require(tseriesChaos)
require(crqa)
require(Hmisc)
require(grid)
require(ggplot2)

setwd("/Users/ymkeverduyn/Desktop/TILBURG UNIVERSITY/YEAR 1 SEM 2/COMPLEX SYSTEMS/Group project/HRV/amateurs/Surrogates")
HRV_data <- read.csv(file="amateur_surrogate_hrv0.csv")

```

```{r}
## temporal dynamics and change ##
num_players <- 5
# Loop through each player's data
for (i in 0:(num_players - 1)) {
  # Extract GSR data for the current player
  player_HRV<- HRV_data[[paste("player", i, sep = "_")]]

  # Convert to a time series object
  TS <- ts(player_HRV)
  y_limits <- c(0, 16)
  # Plot the time series data
  ts.plot(ylim= y_limits, TS, main = paste("Original RMSSD Time Series - Surrogate Player", i))
}
```


```{r}
num_players <- 5
for (i in 0:(num_players - 1)) {
  player_HRV<- HRV_data[[paste("player", i, sep = "_")]]
  TS <- ts(player_HRV)
  differences <- diff(TS)
  ts.plot(differences, main = paste("Discrete Differences of RMSSD - Surrogate Player", i))
}
```
```{r}
num_players <- 5
for (i in 0:(num_players - 1)) {
  player_HRV<- HRV_data[[paste("player", i, sep = "_")]]
  differences <- diff(player_HRV)
  lhd <- density(differences)
  plot(lhd, main = paste("Density of Discrete Differences in RMSSD - Surrogate Player", i))
}
```


```{r}
num_players <- 5
for (i in 0:(num_players - 1)) {
  player_HRV<- HRV_data[[paste("player", i, sep = "_")]]
  player_data <- data.frame(HRV = player_HRV)
  
  # Calculate a lead and a lag and estimate velocity
  player_data$HRV_lag1 <- Lag(player_data$HRV, 1)
  player_data$HRV_lead1 <- Lag(player_data$HRV, -1)
  player_data$HRV_vel <- (player_data$HRV_lead1 - player_data$HRV_lag1) / 2

  # Plot change in time series
  plot(player_data$HRV_vel, type='l', xlab = "Time", ylab = "Change in HRV",
       main = paste("Change in RMSSD Time Series - Surrogate Player", i))
}
```

```{r}
#Attractor dynamics through regression, I did the surrogate testing on the plots but not for the linear models because p-values are all non significant
num_players <- 5
for (i in 0:(num_players - 1)) {
  player_HRV<- HRV_data[[paste("player", i, sep = "_")]]
  player_data <- data.frame(HRV = player_HRV)
  
  # Calculate a lead and a lag and estimate velocity
  player_data$HRV_lag1 <- Lag(player_data$HRV, 1)
  player_data$HRV_lead1 <- Lag(player_data$HRV, -1)
  player_data$HRV_vel <- (player_data$HRV_lead1 - player_data$HRV_lag1) / 2

  # Plot change in time series
  plot(player_data$HRV, player_data$HRV_vel, xlab = 'HRV', ylab='Change in HRV', 
       main = paste("Attractor Dynamics of RMSSD - Surrogate Player", i), pch=20)
}
```

```{r}
num_players <- 5
for (i in 0:(num_players - 1)) {
 player_HRV<- HRV_data[[paste("player", i, sep = "_")]]
 player_data <- data.frame(HRV = player_HRV, window = seq_along(player_HRV))
  
  # Calculate a lead and a lag and estimate velocity
  player_data$HRV_lag1 <- Lag(player_data$HRV, 1)
  player_data$HRV_lead1 <- Lag(player_data$HRV, -1)
  player_data$HRV_vel <- (player_data$HRV_lead1 - player_data$HRV_lag1) / 2

  p <- ggplot(data=player_data, aes(x=window, y=HRV)) +
    geom_segment(aes(xend=window, yend=HRV + HRV_vel), arrow=arrow(length=unit(.2, "cm"))) +
    stat_density2d(aes(colour=after_stat(level))) +
    labs(title = paste("Vector Density Plot RMSSD - Surrogate Player", i), x= "Time Window", y = "HRV")
  print(p)
}
```

 

